### ISSUE TITLE
add  your login in readme file

### ISSUE THREAD

**Issue by lgliducik** [lgliducik/unit-t#1]
Спасибо!
Если не сложно склонируйте мой проект, сделайте таску в новой ветке, потом  пул реквест. 
И если не сложно добавьте меня в свой проект (lgliducik) и создайте, пожалуйста,  мне таску)

**Comment by eugenepro777** [comment]
Задание принял

**Comment by eugenepro777** [comment]
Спушил ветку в репозиторий

**Comment by lgliducik** [comment]
задача принята
